export const defaultDataLayer = () => ({
  isMobile: true,
  gaId: process.env.GA_ID || '',
  optimizeId: process.env.OPTIMIZE_ID || '',
  newStack: true,
});

export const events = {
  ADD_TO_CART_CLICK: 'addToCartClick',
  ADD_TO_CART_SUCCESS: 'addToCartSuccess',
  ADD_TO_WISHLIST_SUCCESS: 'addToWishlistSuccess',
  PRODUCT_PAGE_VIEW_CLIENT: 'productPageViewClient',
  USER_DATA_FETCH: 'userDataFetched',
  USER_LOGOUT: 'userLoggedout',
  NOTIFY_ME: 'notifyMe',
  NOTIFY_ME_SUBMIT: 'notifyMeSubmit',
  GAMOOGA_CART_SUCCESS: 'gamoogaCartSuccess',
  VARIANT_CHANGE_ON_PD: 'variantChangePD',
  RATE_PRODUCT_CLICK: 'rateProductClick',
  REMOVE_ROM_WISHLIST: 'removeFromWishlist',
  REVIEW_IMAGE_CLICK: 'reviewImageClick',
  REVIEW_FILTER_SELECTED: 'filterSelected',
  REVIEW_SORT_SELECTED: 'sortSelected',
  IMAGE_GRID_PAGE: 'imageGridPage',
  VIEW_SIMILAR_CLICK: 'viewSimilarClick',
  OFFERS_TAG_CLICK: 'offersTagClick',
  ALL_SHADES_CLICK: 'allShadesClick',
  REVIEW_IMAGE_CLOSE: 'reviewImageClose',
  ALL_REVIEW_CLICK: 'allReviewsClick',
  COMBO_REVIEW_CLICK: 'comboReviewClicked',
  GUIDE_CLICK: 'guideClick',
  GUIDE_OPENED: 'guideOpened',
  PRODUCT_VIDEO_PLAY: 'productVideoPlay',
  SIZE_CHART_CLICK: 'sizeChartClick',
  VOICE_SEARCH_CLICK: 'voiceSearchClick',
  VOICE_SEARCH_TRY_AGAIN: 'voiceSearchTryAgain',
  CLICK_INTERACTION: 'clickInteractionNew',
  BANNER_EVENTS: 'bannerEvents',
  VERLOOP_LOAD: 'loadVerloop',
  VERLOOP_LOGOUT: 'logoutVerloop',
  CUSTOM_BANNER_CLICK: 'customBannerClick',
  CHECK_PIN_CODE: 'checkPinCode',
  READ_MORE_CLICK: 'READ_MORE_CLICK',
  CAROUSAL_SLIDE_CHANGE: 'carousalSlideChange',
  PDP_IMAGE_CLICK: 'imageInCarouselClick',
  PDP_IMAGE_ENLARGE_ICON_CLICK: 'imageEnlargeIconClick',
  CONFIG_EXPIRED: 'reactConfigExpired',
  PDP_CAROUSAL_SWIPES: 'PDP_CAROUSAL_SWIPES',
  PDP_VIDEO_SWIPED: 'PDP_VIDEO_SWIPED',
};
