export const data = {
  title: 'Customers Also Bought',
  design: 'horizontal_slider',
  has_more: true,
  position: 1,
  products: [
    {
      catalog_tag: [
        'nykaa',
        'natural',
        'pro',
        'nykaaRetail',
        'men',
        'quickCommerce',
      ],
      discount: 15,
      is_saleable: true,
      type: 'simple',
      brand_ids: ['20478'],
      category_ids: [
        '2',
        '31',
        '587',
        '867',
        '1300',
        '5926',
        '5991',
        '5992',
        '5996',
        '6309',
        '6361',
        '6388',
        '7287',
        '7303',
        '7306',
        '8377',
        '71413',
        '64694',
        '64998',
      ],
      sku: 'NYKAB00000508',
      slug: 'nykaa-illuminate-vitamin-c-moisturizer/snsp/2735781',
      offers: [
        {
          id: 1060100,
          name: 'Nykaa SkinRX Offer',
          description: 'Extra 10% Off On All Orders ! Only For New Customers',
          priority: 2,
          platformList: ['IOS', 'ANDROID'],
          offerLabel: null,
          bxgyMrpFlag: false,
          regions: null,
          offerSimpleActionType: 'by_percent',
          gmcVariables: {
            discountQty: null,
            discountAmount: 10,
            discountStep: null,
            discountCapAmount: null,
          },
          offerTag: 'SelectProd',
          catalog_tag: 'nykaa, men',
          offer_start_date: '2025-01-01 05:00:00',
          offer_end_date: '2025-02-01 04:58:00',
          customer_group: '0,11,1,15,16,7,8,9',
          countries: [],
        },
        {
          id: 1060102,
          name: 'Nykaa SKINRX Offer',
          description: 'Extra 10% Off On All Orders! Only For New Customers',
          priority: 1,
          platformList: ['MSITE'],
          offerLabel: null,
          bxgyMrpFlag: false,
          regions: null,
          offerSimpleActionType: 'by_percent',
          gmcVariables: {
            discountQty: null,
            discountAmount: 10,
            discountStep: null,
            discountCapAmount: null,
          },
          offerTag: 'SelectProd',
          catalog_tag: 'nykaa, men',
          offer_start_date: '2025-01-01 05:00:00',
          offer_end_date: '2025-02-01 04:58:00',
          customer_group: '0,1,15,16,6,7,8,9',
          countries: [],
        },
      ],
      expdt: '2026-06-15',
      pack_size: '50gm',
      parent_id: '2735781',
      nykaaman_offer_ids: [1060100, 1060102],
      offer_ids: [1060100, 1060102],
      button_text: 'Add to Bag',
      media: [
        {
          type: 'image',
          url: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/1/5/1551477NYKAB00000508_1.jpg',
        },
        {
          type: 'image',
          url: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/1/5/1551477NYKAB00000508_2.jpg',
        },
        {
          type: 'image',
          url: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/1/5/1551477NYKAB00000508_3.jpg',
        },
        {
          type: 'image',
          url: 'https://images-static.nykaa.com/media/tr:h-800,w-800,cm-pad_resize/consc/cruelty.jpg',
        },
        {
          type: 'image',
          url: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/1/5/1551477NYKAB00000508_4.jpg',
        },
        {
          type: 'image',
          url: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/1/5/1551477NYKAB00000508_5.jpg',
        },
        {
          type: 'image',
          url: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/1/5/1551477NYKAB00000508_6.jpg',
        },
        {
          type: 'image',
          url: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/1/5/1551477NYKAB00000508_7.jpg',
        },
        {
          type: 'image',
          url: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/1/5/1551477NYKAB00000508_8.jpg',
        },
      ],
      primary_categories: [
        {
          l1: {
            id: '8377',
            name: 'Skin',
          },
          l2: {
            id: '8393',
            name: 'Moisturizers',
          },
          l3: {
            id: '8394',
            name: 'Face Moisturizer & Day Cream',
          },
        },
      ],
      mrp_freeze: false,
      quantity: 2669,
      object_type: 'product',
      offer_count: 2,
      id: '2735781',
      name: 'Nykaa Skinrx Illuminate + Vitamin C Face Day Moisturizer For Radiant Skin With SPF 15 Normal To Dry Skin',
      final_price: 339,
      price: 399,
      gludo_stock: true,
      rating: 4.2,
      rating_count: 5122,
      offer_message: 'Offer Available',
      offer_id: null,
      dynamic_tags: ['OFFER'],
      image_url:
        'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/1/5/1551477NYKAB00000508_1.jpg',
      is_backorder: 0,
      fbn: 0,
      show_wishlist_button: 0,
      is_lux: 0,
      brand_name: 'Nykaa SKINRX',
      from_gludo: 1,
      explore_more: null,
      is_kit_combo: null,
    },
  ],
  widget_type: 'cab',
  is_recently_viewed: false,
  show_view_all: true,
};
