export const data = {
  response: {
    reviewData: {
      '55965216': {
        id: 55965216,
        childId: 7066975,
        title: 'WOW, just WOW',
        description:
          "It's really worth the hype. Lippy is just an amazing colour which suits any skin type and any outfit. It's mild red colour. Perfect for any occasion. I don't know whether it's long lasting or not. It will take time to settle! Once it gets dry you'll be comfortable. Otherwise it's kinda sticky. I've uploaded unfiltered photo. So it's the original exact colour which you can refer. ",
        name: 'Anonymous',
        createdOn: '2025-01-09 15:53:55',
        reviewCreationText: '09/01/2025',
        likeCount: 0,
        rating: 5,
        images: [],
        customerProfileUrl:
          'https://images-static.nykaa.com/prod-review/default_profile_image.png',
        tags: null,
        metaData: null,
        userImageCount: null,
        userReviewCount: null,
        proUser: false,
        label: 'Verified Buyer',
        encryptedUserId: 'dc984iQ57GPzyjy6FAa1Hw==',
        reviewCreationTextV2: '2 weeks ago',
        isBuyer: true,
        isLikedByUser: false,
      },
      '56015872': {
        id: 56015872,
        childId: 7066978,
        title: 'Excellent ',
        description:
          "2nd one is saucy a bit dark shade for fair tone but it's very pigmented n stay is awesome ",
        name: 'Japneet Kaur',
        createdOn: '2025-01-13 19:07:38',
        reviewCreationText: '13/01/2025',
        likeCount: 0,
        rating: 4,
        images: [],
        customerProfileUrl:
          'https://images-static.nykaa.com/media/userprofile/prod-review/j.jpg',
        tags: null,
        metaData: null,
        userImageCount: null,
        userReviewCount: null,
        proUser: false,
        label: 'Verified Buyer',
        encryptedUserId: 'ZTJLpnK7YGK4VNPJ4XcJgA==',
        reviewCreationTextV2: '14 days ago',
        isBuyer: true,
        isLikedByUser: false,
      },
      '56015889': {
        id: 56015889,
        childId: 11082828,
        title: 'Excellent ',
        description:
          "1st one Is irresistible it's bit dark for fair tone but stay is awesome ",
        name: 'Japneet Kaur',
        createdOn: '2025-01-13 19:08:49',
        reviewCreationText: '13/01/2025',
        likeCount: 0,
        rating: 4,
        images: [],
        customerProfileUrl:
          'https://images-static.nykaa.com/media/userprofile/prod-review/j.jpg',
        tags: null,
        metaData: null,
        userImageCount: null,
        userReviewCount: null,
        proUser: false,
        label: 'Verified Buyer',
        encryptedUserId: 'ZTJLpnK7YGK4VNPJ4XcJgA==',
        reviewCreationTextV2: '14 days ago',
        isBuyer: true,
        isLikedByUser: false,
      },
      '56063745': {
        id: 56063745,
        childId: 11082828,
        title: 'Maybelline Irresistible ',
        description: 'Beautiful shade ',
        name: 'Rose',
        createdOn: '2025-01-17 19:00:19',
        reviewCreationText: '17/01/2025',
        likeCount: 0,
        rating: 5,
        images: [],
        customerProfileUrl:
          'https://images-static.nykaa.com/media/userprofile/prod-review/r.jpg',
        tags: null,
        metaData: null,
        userImageCount: null,
        userReviewCount: null,
        proUser: false,
        label: 'Verified Buyer',
        encryptedUserId: '4UszD3QsLTHCTDllzFN8KQ==',
        reviewCreationTextV2: '10 days ago',
        isBuyer: true,
        isLikedByUser: false,
      },
      '55879864': {
        id: 55879864,
        childId: 11082828,
        title: 'Irresistible ',
        description:
          'This is seriously irresistible this shade is good with any skin tone I have a medium skin tone it was looking so good for office and good to go for any normal occasions ',
        name: 'Kajal Singh',
        createdOn: '2025-01-02 17:55:47',
        reviewCreationText: '02/01/2025',
        likeCount: 0,
        rating: 5,
        images: [],
        customerProfileUrl:
          'https://images-static.nykaa.com/media/userprofile/prod-review/k.jpg',
        tags: null,
        metaData: null,
        userImageCount: null,
        userReviewCount: null,
        proUser: false,
        label: 'Verified Buyer',
        encryptedUserId: 'IksoLuOdcglDbnuXjUb1kg==',
        reviewCreationTextV2: '3 weeks ago',
        isBuyer: true,
        isLikedByUser: false,
      },
      '56160409': {
        id: 56160409,
        childId: 7066975,
        title: 'Maybelline lipstick.',
        description: 'So, hydrating and long-lasting.',
        name: 'Swati Sehrawat',
        createdOn: '2025-01-25 15:39:39',
        reviewCreationText: '2 days ago',
        likeCount: 0,
        rating: 5,
        images: [],
        customerProfileUrl:
          'https://images-static.nykaa.com/media/userprofile/prod-review/s.jpg',
        tags: null,
        metaData: null,
        userImageCount: null,
        userReviewCount: null,
        proUser: false,
        label: 'Verified Buyer',
        encryptedUserId: 'PKEBO0jRJ4XHFb+jNnzc2g==',
        reviewCreationTextV2: '2 days ago',
        isBuyer: true,
        isLikedByUser: false,
      },
      '56055819': {
        id: 56055819,
        childId: 7066981,
        title: 'It’s wow ',
        description: 'It’s amazing ',
        name: 'Abeer sethi',
        createdOn: '2025-01-17 03:05:28',
        reviewCreationText: '17/01/2025',
        likeCount: 0,
        rating: 5,
        images: [],
        customerProfileUrl:
          'https://images-static.nykaa.com/media/userprofile/prod-review/a.jpg',
        tags: null,
        metaData: null,
        userImageCount: null,
        userReviewCount: null,
        proUser: false,
        label: 'Verified Buyer',
        encryptedUserId: 'TpuiA/u562MKyFUUAdTAfg==',
        reviewCreationTextV2: '10 days ago',
        isBuyer: true,
        isLikedByUser: false,
      },
      '55995627': {
        id: 55995627,
        childId: 11082828,
        title: 'Nude shade ….just wow.\uD83E\uDD29 ',
        description:
          'This is real shade without any filter, and its gorgeous\uD83D\uDE0D good for Indian skin tone',
        name: 'Jyoti',
        createdOn: '2025-01-12 01:37:13',
        reviewCreationText: '12/01/2025',
        likeCount: 0,
        rating: 5,
        images: [],
        customerProfileUrl:
          'https://images-static.nykaa.com/media/userprofile/prod-review/j.jpg',
        tags: null,
        metaData: null,
        userImageCount: null,
        userReviewCount: null,
        proUser: false,
        label: 'Verified Buyer',
        encryptedUserId: '+dUDo1D9SQ9DOtYC0sKD0w==',
        reviewCreationTextV2: '15 days ago',
        isBuyer: true,
        isLikedByUser: false,
      },
      '55890470': {
        id: 55890470,
        childId: 7066981,
        title: 'Long lasting and transfer proof',
        description:
          'It is really long lasting and transfer proof. Unfortunately the colour looks too purple on my lips though it looks pinkish in the pic.',
        name: 'Shemlen Phom',
        createdOn: '2025-01-03 16:00:47',
        reviewCreationText: '03/01/2025',
        likeCount: 0,
        rating: 3,
        images: [],
        customerProfileUrl:
          'https://images-static.nykaa.com/media/userprofile/prod-review/s.jpg',
        tags: null,
        metaData: null,
        userImageCount: null,
        userReviewCount: null,
        proUser: false,
        label: 'Verified Buyer',
        encryptedUserId: '0XJW7I5t/CYgBPprYbgA7g==',
        reviewCreationTextV2: '3 weeks ago',
        isBuyer: true,
        isLikedByUser: false,
      },
      '56072263': {
        id: 56072263,
        childId: 7066975,
        title: 'Good.',
        description: 'Nice one.',
        name: 'Akshara Jaiswal',
        createdOn: '2025-01-18 14:59:57',
        reviewCreationText: '18/01/2025',
        likeCount: 0,
        rating: 4,
        images: [],
        customerProfileUrl:
          'https://images-static.nykaa.com/media/userprofile/prod-review/a.jpg',
        tags: null,
        metaData: null,
        userImageCount: null,
        userReviewCount: null,
        proUser: false,
        label: 'Verified Buyer',
        encryptedUserId: 'U3BYjSkTzhsurfd3Q3pIdQ==',
        reviewCreationTextV2: '9 days ago',
        isBuyer: true,
        isLikedByUser: false,
      },
      '56098367': {
        id: 56098367,
        childId: 7066981,
        title: 'Maybelline New York Super Stay',
        description:
          "Fallen in love with this color. It's my exact lip shade. It's camouflaged into my lips. In mall it was 800rs. Here I got it for around 600rs. Happy about it. Witty is cool \uD83D\uDE0E",
        name: 'Srinidhi Thiagarajan',
        createdOn: '2025-01-20 18:37:03',
        reviewCreationText: '20/01/2025',
        likeCount: 0,
        rating: 5,
        images: [],
        customerProfileUrl:
          'https://images-static.nykaa.com/media/userprofile/prod-review/s.jpg',
        tags: null,
        metaData: null,
        userImageCount: null,
        userReviewCount: null,
        proUser: false,
        label: 'Verified Buyer',
        encryptedUserId: 'NDI0dhsewogD9+VpUwHICg==',
        reviewCreationTextV2: '7 days ago',
        isBuyer: true,
        isLikedByUser: false,
      },
      '55896049': {
        id: 55896049,
        childId: 7066975,
        title: 'Awesome ',
        description:
          'Slightly light color does not like the bottle color but shade is good suitable for every skin tone',
        name: 'bony sarkar',
        createdOn: '2025-01-03 23:16:05',
        reviewCreationText: '03/01/2025',
        likeCount: 0,
        rating: 4,
        images: [],
        customerProfileUrl:
          'https://images-static.nykaa.com/media/userprofile/prod-review/b.jpg',
        tags: null,
        metaData: null,
        userImageCount: null,
        userReviewCount: null,
        proUser: false,
        label: 'Verified Buyer',
        encryptedUserId: 'gxJbUbkNWaOCNw40FqmaQw==',
        reviewCreationTextV2: '3 weeks ago',
        isBuyer: true,
        isLikedByUser: false,
      },
      '56050029': {
        id: 56050029,
        childId: 11082829,
        title: 'Amazing ',
        description:
          'Perfect shade for fair and medium skin tone people \r\nLong lasting stay smells like vanilla \uD83D\uDC95',
        name: 'vedangi sharma',
        createdOn: '2025-01-16 16:22:18',
        reviewCreationText: '16/01/2025',
        likeCount: 0,
        rating: 5,
        images: [],
        customerProfileUrl:
          'https://images-static.nykaa.com/prod-review/pro_review_profile_image.png',
        tags: null,
        metaData: null,
        userImageCount: null,
        userReviewCount: null,
        proUser: true,
        label: 'Verified Professional',
        encryptedUserId: 'aTtQuuDhMW3RkTWIU53Jgg==',
        reviewCreationTextV2: '11 days ago',
        isBuyer: true,
        isLikedByUser: false,
      },
      '55848762': {
        id: 55848762,
        childId: 7066980,
        title: 'Red as hell ',
        description:
          'Amazing lip shade I have ever had. Just like fire \uD83D\uDD25\uD83D\uDD25 \r\nThank you so much nykaa\uD83D\uDC8B\uD83D\uDC8B',
        name: 'Alshifa Ekshan Shaikh',
        createdOn: '2024-12-30 19:28:11',
        reviewCreationText: '30/12/2024',
        likeCount: 0,
        rating: 5,
        images: [],
        customerProfileUrl:
          'https://images-static.nykaa.com/media/userprofile/prod-review/a.jpg',
        tags: null,
        metaData: null,
        userImageCount: null,
        userReviewCount: null,
        proUser: false,
        label: 'Verified Buyer',
        encryptedUserId: 'bfUCxwSIjx29MO/Vf9ad3g==',
        reviewCreationTextV2: '4 weeks ago',
        isBuyer: true,
        isLikedByUser: false,
      },
      '56090001': {
        id: 56090001,
        childId: 11082829,
        title: 'Good liquid lipstick.',
        description:
          'It’s not bad lipstick. It has a good shine, and non-sticky but it’s a bit darker shade than it’s shown in the picture.',
        name: 'Elsa NaKhleh',
        createdOn: '2025-01-20 01:08:47',
        reviewCreationText: '20/01/2025',
        likeCount: 0,
        rating: 4,
        images: [],
        customerProfileUrl:
          'https://images-static.nykaa.com/media/userprofile/prod-review/e.jpg',
        tags: null,
        metaData: null,
        userImageCount: null,
        userReviewCount: null,
        proUser: false,
        label: 'Verified Buyer',
        encryptedUserId: 'EulJmBlGy3rfEw/TKD7DZw==',
        reviewCreationTextV2: '7 days ago',
        isBuyer: true,
        isLikedByUser: false,
      },
      '55907671': {
        id: 55907671,
        childId: 7066975,
        title: 'Long lasting',
        description:
          "Great colour, long lasting, and has a lot of shine. Good quality, smells nice. I took off 1 star because the product images shows that this is red/maroon colour, but it's actually a dark nude/pink. Colour is still good, but I bought this wanting a red lipstick. Lipstick lasted through dinner",
        name: 'chetana',
        createdOn: '2025-01-04 22:33:44',
        reviewCreationText: '04/01/2025',
        likeCount: 1,
        rating: 4,
        images: [],
        customerProfileUrl:
          'https://images-static.nykaa.com/media/userprofile/prod-review/c.jpg',
        tags: null,
        metaData: null,
        userImageCount: null,
        userReviewCount: null,
        proUser: false,
        label: 'Verified Buyer',
        encryptedUserId: 'Drn4+KmLWWig3nK9/YoyQw==',
        reviewCreationTextV2: '3 weeks ago',
        isBuyer: true,
        isLikedByUser: false,
      },
      '56094922': {
        id: 56094922,
        childId: 7066976,
        title: 'Amazing as always ',
        description:
          "I'm fair in complex... Nd the shade is peachy ... on my lips it's shows more like a nude shade with tint of orange shade ... good for everyday natural look ... Pigmentation is oms like always ... go for it ... will be posting pics for the reference ... one is under the natural light nd other is in the home light respectively...",
        name: 'Sheetal Dangwal',
        createdOn: '2025-01-20 14:52:46',
        reviewCreationText: '20/01/2025',
        likeCount: 0,
        rating: 4,
        images: [],
        customerProfileUrl:
          'https://images-static.nykaa.com/media/userprofile/prod-review/s.jpg',
        tags: null,
        metaData: null,
        userImageCount: null,
        userReviewCount: null,
        proUser: false,
        label: 'Verified Buyer',
        encryptedUserId: 'vUEQS6FWjEej6mNSR1xVtQ==',
        reviewCreationTextV2: '7 days ago',
        isBuyer: true,
        isLikedByUser: false,
      },
      '55981930': {
        id: 55981930,
        childId: 14474072,
        title: 'Must buy',
        description: 'Must have color in your collection ',
        name: 'professor r',
        createdOn: '2025-01-10 21:37:40',
        reviewCreationText: '10/01/2025',
        likeCount: 0,
        rating: 5,
        images: [],
        customerProfileUrl:
          'https://images-static.nykaa.com/media/userprofile/prod-review/p.jpg',
        tags: null,
        metaData: null,
        userImageCount: null,
        userReviewCount: null,
        proUser: false,
        label: 'Verified Buyer',
        encryptedUserId: 'qRLGAHtvBPQn7ftvs0fPiA==',
        reviewCreationTextV2: '2 weeks ago',
        isBuyer: true,
        isLikedByUser: false,
      },
    },
  },
};